global:
  resolve_timeout: 3m
  slack_api_url: 

receivers:
- name: default-receiver
  slack_configs:
  - channel: '#channels'
    send_resolved: true
    username: '{{ template "slack.default.username" . }}'
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]  {{ .CommonLabels.alertname }} ({{ .CommonLabels.severity }})         
    pretext: '{{ template "slack.default.pretext" . }}'
    text: >-
      {{ range .Alerts -}}
      *Alert:* {{ .Annotations.summary }}
 
      *Description:* {{ .Annotations.description }}
  

      *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}    
    footer: '{{ template "slack.default.footer" . }}'
    fallback: '{{ template "slack.default.fallback" . }}'
    callback_id: '{{ template "slack.default.callbackid" . }}'
    icon_emoji: '{{ template "slack.default.iconemoji" . }}'
    icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
  

route:
  group_by:
  - alertname
  - job
  - instance
  group_interval: 1m
  group_wait: 10s
  receiver: default-receiver
  repeat_interval: 30m